const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "English Dictionary",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Words",
            "description": "Endpoints",
        }
    ],
    definitions: {
        Word: {
            word: "hello",
        },
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/server.js')
})
